---
# hadoop/tasks/main.yml

- name: Remove old hadoop users
  user:
    name: "{{ item }}"
    state: absent
  with_items:
    - hadoop
    - yarn

- name: Remove old hadoop user home
  file:
    path: "{{ hadoop_user_home }}"
    state: absent

- name: Create hadoop group
  group: name=hadoop

- name: Add hadoop users
  user:
    name: "{{ item }}"
    group: hadoop
    comment: "Hadoop {{ item }}"
    home: "{{ hadoop_user_home }}"
    shell: "/bin/bash"
  with_items:
    - hadoop

- name: Add hadoop users
  user:
    name: "{{ item }}"
    group: hadoop
    home: "{{ hadoop_user_home }}"
  with_items:
    - yarn

- name: Remove old RSA host key
  local_action:
    module: file
    path: "/tmp/hadoop.id_rsa"
    state: absent
  run_once: yes

- name: Remove old RSA host key
  local_action:
    module: file
    path: "/tmp/hadoop.id_rsa.pub"
    state: absent
  run_once: yes

- name: Generate a new RSA host key
  local_action: command ssh-keygen -q -t rsa -C "" -N "" -f /tmp/hadoop.id_rsa
  run_once: yes
  vars:
    ansible_become: no

- name: Set authorized key
  authorized_key:
    user: hadoop
    state: present
    exclusive: yes
    key: "{{ lookup('file', '/tmp/hadoop.id_rsa.pub') }}"

- name: Remove old known_hosts
  local_action:
    module: file
    path: "/tmp/hadoop.known_hosts"
    state: absent
  run_once: yes

- name: Make known_hosts
  local_action: shell ssh-keyscan {{ item }} >> /tmp/hadoop.known_hosts
  run_once: yes
  with_items: "{{ groups.all }}"
  vars:
    ansible_become: no

- name: Set known_hosts
  copy:
    src: "/tmp/hadoop.known_hosts"
    dest: "{{ hadoop_user_home }}/.ssh/known_hosts"
    owner: "hadoop"
    group: "hadoop"
    mode: "0700"

- name: Copy private key
  copy:
    src: "/tmp/hadoop.id_rsa"
    dest: "{{ hadoop_user_home }}/.ssh/id_rsa"
    owner: "hadoop"
    group: "hadoop"
    mode: "0700"

- name: Copy public key
  copy:
    src: "/tmp/hadoop.id_rsa.pub"
    dest: "{{ hadoop_user_home }}/.ssh/id_rsa.pub"
    owner: "hadoop"
    group: "hadoop"
    mode: "0700"
