---
# hadoop/tasks/main.yml

# https://hadoop.apache.org/docs/r2.7.2/hadoop-project-dist/hadoop-common/SecureMode.html#User_Accounts_for_Hadoop_Daemons
- name: Make dl_dir
  file:
    path: "{{ dl_dir }}"
    state: directory

- name: Download Hadoop 2.7.2
  get_url:
    url: "https://archive.apache.org/dist/hadoop/common/hadoop-2.7.2/hadoop-2.7.2.tar.gz"
    checksum: "sha256:49ad740f85d27fa39e744eb9e3b1d9442ae63d62720f0aabdae7aa9a718b03f7"
    dest: "{{ dl_dir }}/hadoop-2.7.2.tar.gz"
  register: hadoop_dl

- name: Clean Hadoop dir
  file:
    path: "{{ hadoop_home }}"
    state: absent

- name: Make Hadoop home
  file:
    path: "{{ hadoop_home }}"
    state: directory
    owner: hadoop
    group: hadoop
    mode: 0775

- name: Uncompress Hadoop
  unarchive:
    src: "{{ hadoop_dl.dest }}"
    dest: "{{ hadoop_home }}"
    remote_src: yes
    extra_opts: ["--strip-components=1"]
    owner: hadoop
    group: hadoop

- name: Set path for Hadoop
  shell: "echo 'export PATH=$PATH:{{ hadoop_home }}/bin' > /etc/profile.d/hadoop.sh"

- name: Set Hadoop configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ hadoop_conf_dir }}/{{ item }}"
  with_items:
    - core-site.xml
    - hdfs-site.xml
    - mapred-site.xml
    - yarn-site.xml
    - yarn-env.sh
    - hadoop-env.sh
    - slaves

- name: Clean data dir
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ hadoop_data_dir }}"
    - "{{ hadoop_scratch_dir }}"

- name: Make namenode dir
  file:
    path: "{{ item }}"
    state: directory
    owner: hadoop
    group: hadoop
    mode: 0775
  with_items:
    - "{{ hadoop_data_dir }}"
    - "{{ hadoop_scratch_dir }}"
