---
# hadoop/tasks/main.yml

- name: Make dl_dir
  file:
    path: "{{ dl_dir }}"
    state: directory

- name: Download Ignite 2.6.0
  get_url:
    url: "https://www-us.apache.org/dist//ignite/2.6.0/apache-ignite-fabric-2.6.0-bin.zip"
    checksum: "sha512:7dbd1442073557c5125e500e6a267243af8d72f73352fb67bea4b7ab448b8faa803aae03984d781fd96aa89736943b7540b73aa091055d466605ecbe940c32e3"
    dest: "{{ dl_dir }}/apache-ignite-fabric-2.6.0-bin.zip"
  register: ignite_dl

- name: Clean Ignite dir
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ignite_home }}"
    - "/tmp/ignite_temp"

- name: Make Ignite home
  file:
    path: "{{ item }}"
    state: directory
    owner: hadoop
    group: hadoop
    mode: 0775
  with_items:
    - "/tmp/ignite_temp"

- name: Uncompress Ignite
  unarchive:
    src: "{{ ignite_dl.dest }}"
    dest: "/tmp/ignite_temp"
    remote_src: yes
    owner: hadoop
    group: hadoop

- name: Move Ignite
  command: "mv /tmp/ignite_temp/apache-ignite-fabric-2.6.0-bin {{ ignite_home }}"

- name: Set path for Ignite
  shell: "echo 'export PATH=$PATH:{{ ignite_home }}/bin' > /etc/profile.d/ignite.sh"

- name: Clean data dir
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ignite_data_dir }}"

- name: Make data dir
  file:
    path: "{{ item }}"
    state: directory
    owner: hadoop
    group: hadoop
    mode: 0775
  with_items:
    - "{{ ignite_data_dir }}"
