---
# nagios/tasks/main.yml

- name: Install NRPE
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items:
    - nagios-nrpe-server
    - nagios-plugins

- name: Setup NRPE configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ nagios_conf_dir }}/{{ item }}"
  with_items:
    - nrpe.cfg

- name: Restart nagios
  service:
    name: nagios-nrpe-server
    state: restarted

- name: Allow nagios firewall
  ufw: rule=allow port=5666 proto=tcp
