---
# file: roles/java8/tasks/main.yml

- name: Remove apt repo for Java8 package (old oracle java8)
  apt_repository:
    repo: "ppa:webupd8team/java"
    filename: "java8"
    state: absent

- name: Uninstall Oracle Java8 package
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: absent
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default

- name: Remove old environmental variables for Java
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/profile.d/jdk.sh
    - /etc/profile.d/jdk.csh

- name: Install Java8 package
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items:
    - openjdk-8-jdk

- name: Set path for JAVA_HOME
  shell: "echo 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64' > /etc/profile.d/jdk.sh"
