---
# file: roles/common-prep/tasks/main.yml

- name: Upgrade system to current using apt
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600

- name: Register if a reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot if required
  when: reboot_required.exists is defined
  debug:
    msg: "System will reboot"
  notify:
    - restart host
    - wait for host

- name: Install standard packages
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
   - tmux
   - vim
   - wget
   - unzip
   - software-properties-common

- name: Remove annoying default editors
  apt:
    pkg: "{{ item }}"
    state: absent
    update_cache: yes
    cache_valid_time: 3600
  with_items:
   - nano
   - jove

- name: Enable vim syntax highlighting
  lineinfile: dest=/etc/vim/vimrc regexp="^\s*syntax on" line="syntax on"

- name: Configure tmux
  copy:
    src: tmux.conf
    dest: "{{ ansible_user_dir }}/.tmux.conf"

- name: Append hosts
  template:
    src: "hosts.j2"
    dest: "/tmp/hosts.append"

- name: Append hosts
  shell: cat /tmp/hosts.append >> /etc/hosts
