---
# users/tasks/main.yml

- name: Remove old users
  user:
    name: "{{ item }}"
    state: absent
  with_items:
    - mbomhoff

- name: Add users
  user:
    name: "{{ item }}"
    groups:
      - hadoop
      - docker
    home: "/home/{{ item }}"
    shell: "/bin/bash"
    append: yes
  with_items:
    - mbomhoff

- name: Set authorized key
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '../files/' + item + '.pub') }}"
  with_items:
    - mbomhoff
